package:
  name: stock_downloader
  version: "0.0.1"

source:
  git_rev: 0.0.1
  git_url: https://github.com/DogaCUlupinar/stock_downloader.git

requirements:
  build:
    - python
    - setuptools
    - six
    - requests-file
    - requests
    - pytz
    - python-dateutil
    - pandas-datareader
    - pandas
    - numpy

  run:
    - python

test:
  imports: 
    - stock_download

about:
  home: https://github.com/DogaCUlupinar/stock_downloader